name: 📖  Website & Documentation Suggestion
description: Help us improve the Quire website and documentation
labels: [feature]
assignees:
- erin-cecele
- geealbers
body:
- type: markdown
  attributes:
    value: | 
      # Thank you for opening a new issue!
- type: checkboxes
  attributes:
    label: Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.
    description:
    options:
    - label: I have searched the existing issues and determined this is new suggestion.
      required: true    
- type: textarea
  id: reproduce
  attributes:
    label: Idea being proposed
    description: Describe your desired contribution and how it will improve the documentation and/or website.
  validations:
    required: true
- type: dropdown
  id: type
  attributes:
    label: What contribution category does your proposal fall under?
    multiple: true
    options:
    - Fix typo/broken link
    - Copyedit text
    - Propose/write new section
    - Propose/Write article
    - Translate documentation
    - Other
  validations:
    required: true
- type: textarea
  id: supporting_info
  attributes:
    label: Supporting Information
    description: If you have additional files that would be useful in describing your contribution, such as screenshots, attach them by dragging and dropping in the comments below.
  validations:
    required: false
