name: 📖 Website & Documentation Suggestion
description: Help us improve the Quire website and documentation
labels: [feature]
assignees:
- erin-cecele
- geealbers
body:
- type: markdown
  attributes:
    value: |
   
      **Thank you for opening a new issue!**
    
      ⚠ Before submitting your proposal, please review our [Contributing Guidelines](##).
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true      
- type: textarea
  id: reproduce
  attributes:
    label: Idea being proposed
    description: Describe the feature you would like to contribute and how it will help improve Quire.
  validations:
    required: true
- type: dropdown
  id: type
  attributes:
    label: What contribution type category does your proposal fall under.
    multiple: true
    options:
    - Fix typo/broken link
    - Copyedit text
    - Propose/write new section
    - Propose/Write article
    - Translate documentation
- type: textarea
  id: supporting_info
  attributes:
    label: Supporting Information
    description: If you have additional files that would be useful in describing the issue (Terminal output, screenshots, Quire output files) attach them by dragging and dropping in the comments below.
  validations:
    required: false
